### ISSUE TITLE
Update README files to include instructions on how to view menu in-game

### ISSUE THREAD

**Issue by huddhudd** [mizx/pubg-ui#27]
I want to deploy the server with the client. what should I do. Are there helpful tutorials?

**Comment by mizx** [comment]
The project is still in early stages, I'll add setup instructions tonight and will update the readme.

**Comment by huddhudd** [comment]
This project is very good, there are a lot of people concerned about. If not updated, then really a pity. Or tell us how to update it.

**Comment by mizx** [comment]
I updated the README files to provide basic instructions on how to get it to show up in-game.

https://github.com/mizx/pubg-ui/commit/a629ab35133ace79eb722459217ef86031ab05f8

**Comment by huddhudd** [comment]
Thank you
