### ISSUE TITLE
Has been installed on the server.

### ISSUE THREAD

**Issue by huddhudd** [mizx/pubg-ui#29]
47.52.102.58 front.battlegroundsgame.com
47.52.102.58 prod-live-front.playbattlegrounds.com 

Has been installed on the server.
I went into the game and tried it. The effect is not bad.

The author refueling, this is really good.

**Comment by huddhudd** [comment]
weak and weak to ask
Can not start the game. Is it done that has not finished this function yet?

**Comment by mizx** [comment]
Has not been implement yet. Working on friends list first, then will work on getting into game/matchmaking.
